debug: false
graphql: "https://api.thegraph.com/subgraphs/name/kybernetwork/kyberswap-elastic-matic"
positions: ["1239", "1241"]
binance:
  api_key: "test_binance_api_key"
  secret_key: "test_secret_key"
